<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>EmuWorks</AssemblyName>
    <RootNamespace>EmuWorks</RootNamespace>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <SatelliteResourceLanguages>fr</SatelliteResourceLanguages>
  </PropertyGroup>

</Project>
